[workspace]
resolver = "3"
members = [
    "crates/kui-core",
    "crates/kui-wgpu",
    "crates/kui",
    "crates/kui-lua",
    "crates/kui-ffi",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
kui-core = { path = "crates/kui-core" }
kui-wgpu = { path = "crates/kui-wgpu" }
kui = { path = "crates/kui" }

slotmap = "1.0"
rustc-hash = "2"
cosmic-text = { version = "0.12", features = ["shape-run-cache"] }
wgpu = "25"
winit = "0.30"
bytemuck = { version = "1", features = ["derive"] }
pollster = "0.4"
mlua = { version = "0.10", features = ["lua54", "vendored"] }
divan = "0.1"

[profile.dev.package."*"]
opt-level = 2

[profile.bench]
debug = true
