// GENERATED by packages/odin/gen from crates/kui-ffi/include/kui.h - do not
// edit; `nu scripts/odin.nu gen` rewrites it. kui.h is the documentation: every
// name here is the C one without its prefix (kui_open -> open, KuiSpec ->
// Spec, KUI_GROW -> GROW), and KuiStr is Odin's string.
package kui_c

// The library to link: kui_ffi from the system search path by default,
// which -extra-linker-flags:"-L<dir>" points at a build. Override with
// -define:KUI_LIB=<name or relative path>.
KUI_LIB :: #config(KUI_LIB, "system:kui_ffi")
foreign import lib { KUI_LIB }

Str :: string

// -- Opaque handles
Ctx :: struct {}
Value :: struct {}
ReplySink :: struct {}

// -- Constants (the header's #defines and anonymous enums)
ABI_VERSION :: 25

MIN_FIT :: -1.0
MIN_NONE :: -2.0

WINDOW_MAIN :: 0

WINDOW_KIND_NORMAL :: 0
WINDOW_KIND_POPUP :: 1

DISMISS_OUTSIDE :: 0
DISMISS_ESCAPE :: 1

OPTION_AS_ALT_NONE :: 0
OPTION_AS_ALT_LEFT :: 1
OPTION_AS_ALT_RIGHT :: 2
OPTION_AS_ALT_BOTH :: 3

FIT :: 0
GROW :: 1
FIXED :: 2
PERCENT :: 3
CALC :: 4

COLUMN :: 0
ROW :: 1
TABLE :: 2

START :: 0
CENTER :: 1
END :: 2
SPACE_BETWEEN :: 3
SPACE_AROUND :: 4
SPACE_EVENLY :: 5
BASELINE :: 6

QUAD_SOLID :: 0
QUAD_GLYPH_MASK :: 1
QUAD_GLYPH_COLOR :: 2
QUAD_IMAGE :: 3
QUAD_GLYPH_SUBPIXEL :: 4
QUAD_SHADOW :: 5
QUAD_SEGMENT :: 6
QUAD_FRAGMENT :: 7
QUAD_TEXTURE :: 8

SAMPLING_LINEAR :: 0
SAMPLING_NEAREST :: 1

FIT_FILL :: 0
FIT_CONTAIN :: 1
FIT_COVER :: 2

FONT_SANS :: 0
FONT_SERIF :: 1
FONT_MONO :: 2

WRAP_WORD :: 0
WRAP_GLYPH :: 1
WRAP_NONE :: 2
WRAP_BREAK_SPACES :: 3

SPAN_BOLD :: 1
SPAN_ITALIC :: 2
SPAN_UNDERLINE :: 4
SPAN_STRIKETHROUGH :: 8

DECO_UNDERLINE :: 1
DECO_STRIKETHROUGH :: 2

UNDERLINE_SOLID :: 0
UNDERLINE_WAVY :: 1
UNDERLINE_DOTTED :: 2

CLIP :: 1
SCROLL_X :: 2
SCROLL_Y :: 4

KEY_LEFT :: 0
KEY_RIGHT :: 1
KEY_UP :: 2
KEY_DOWN :: 3
KEY_HOME :: 4
KEY_END :: 5
KEY_PAGE_UP :: 6
KEY_PAGE_DOWN :: 7
KEY_BACKSPACE :: 8
KEY_DELETE :: 9
KEY_ENTER :: 10
KEY_TAB :: 11
KEY_SELECT_ALL :: 12
KEY_ESCAPE :: 13
KEY_UNDO :: 14
KEY_REDO :: 15

MOD_SHIFT :: 1
MOD_WORD :: 2
MOD_DOC :: 4

KMOD_SHIFT :: 1
KMOD_CTRL :: 2
KMOD_ALT :: 4
KMOD_SUPER :: 8

KLOCK_CAPS :: 16
KLOCK_NUM :: 32
KLAYOUT_NONLATIN :: 64
KLOC_LEFT :: 256
KLOC_RIGHT :: 512
KLOC_NUMPAD :: 768

EDIT_MULTILINE :: 1
EDIT_AUTOFOCUS :: 2
EDIT_WRAP :: 4

FLOAT_NONE :: 0
FLOAT_PARENT :: 1
FLOAT_VIEWPORT :: 2

WINDOW_NONE :: 0
WINDOW_DRAG :: 1
WINDOW_CLOSE :: 2
WINDOW_MINIMIZE :: 3
WINDOW_MAXIMIZE :: 4

EASE_OUT :: 0
EASE_LINEAR :: 1
EASE_IN :: 2
EASE_IN_OUT :: 3
EASE_SPRING :: 4
EASE_BOUNCY :: 5
EASE_SMOOTH :: 6
EASE_SNAPPY :: 7

CMD_START_DRAG :: 1
CMD_CLOSE :: 2
CMD_MINIMIZE :: 3
CMD_TOGGLE_MAXIMIZE :: 4
CMD_OPEN :: 5
CMD_SET_SIZE :: 6
CMD_FOCUS :: 7
CMD_REDRAW :: 8

REPEAT_NORMAL :: 0
REPEAT_REVERSE :: 1
REPEAT_ALTERNATE :: 2
REPEAT_ALTERNATE_REVERSE :: 3

KF_AT :: 1
KF_WIDTH :: 2
KF_HEIGHT :: 4
KF_BG :: 8
KF_RADIUS :: 16
KF_OPACITY :: 32

GRADIENT_LINEAR :: 0
GRADIENT_RADIAL :: 1

ENTER_OFFSET :: 1
ENTER_WIDTH :: 2
ENTER_HEIGHT :: 4
ENTER_BG :: 8
ENTER_RADIUS :: 16
ENTER_OPACITY :: 32

SCROLLBAR_VISIBLE :: 1
SCROLLBAR_HIDDEN :: 2
SCROLLBAR_AUTO :: 3

OVERSCROLL_AUTO :: 1
OVERSCROLL_CONTAIN :: 2

SCROLL_AXES_BOTH :: 1
SCROLL_AXES_X :: 2
SCROLL_AXES_Y :: 3

EXPANDED_COLLAPSED :: 1
EXPANDED_EXPANDED :: 2

LIVE_OFF :: 0
LIVE_POLITE :: 1
LIVE_ASSERTIVE :: 2

CURSOR_DEFAULT :: 1
CURSOR_TEXT :: 2
CURSOR_POINTER :: 3
CURSOR_GRAB :: 4
CURSOR_GRABBING :: 5
CURSOR_NOT_ALLOWED :: 6
CURSOR_EW_RESIZE :: 7
CURSOR_NS_RESIZE :: 8
CURSOR_NWSE_RESIZE :: 9
CURSOR_NESW_RESIZE :: 10

ROLE_NONE :: 1
ROLE_BUTTON :: 2
ROLE_CHECKBOX :: 3
ROLE_RADIO :: 4
ROLE_SWITCH :: 5
ROLE_SLIDER :: 6
ROLE_TAB :: 7
ROLE_TAB_LIST :: 8
ROLE_LINK :: 9
ROLE_HEADING :: 10
ROLE_LIST :: 11
ROLE_LIST_ITEM :: 12
ROLE_IMAGE :: 13
ROLE_DIALOG :: 14
ROLE_GROUP :: 15
ROLE_WINDOW :: 16
ROLE_TITLE_BAR :: 17
ROLE_STATIC_TEXT :: 18
ROLE_TEXT_INPUT :: 19
ROLE_MULTILINE_TEXT_INPUT :: 20
ROLE_SCROLL_VIEW :: 21
ROLE_LINE :: 22
ROLE_RADIO_GROUP :: 23
ROLE_MENU :: 24
ROLE_MENU_ITEM :: 25
ROLE_TERMINAL :: 26

ORIENTATION_HORIZONTAL :: 1
ORIENTATION_VERTICAL :: 2

VALUE_NOW :: 1
VALUE_MIN :: 2
VALUE_MAX :: 4
VALUE_CARET :: 8
VALUE_ANCHOR :: 16
VALUE_CARET_SOLID :: 32
VALUE_STEP :: 64

ACCESS_CLICK :: 1
ACCESS_FOCUS :: 2
ACCESS_BLUR :: 4
ACCESS_SET_VALUE :: 8
ACCESS_INCREMENT :: 16
ACCESS_DECREMENT :: 32
ACCESS_SCROLL_INTO_VIEW :: 64
ACCESS_SCROLL_UP :: 128
ACCESS_SCROLL_DOWN :: 256
ACCESS_SCROLL_LEFT :: 512
ACCESS_SCROLL_RIGHT :: 1024
ACCESS_SET_TEXT_SELECTION :: 2048
ACCESS_REPLACE_SELECTED_TEXT :: 4096

ACCESS_HAS_VALUE :: 1
ACCESS_HAS_SELECTION :: 2
ACCESS_FOCUSED :: 4
ACCESS_CHECKED_SET :: 8
ACCESS_CHECKED :: 16
ACCESS_HAS_NUMBER :: 32
ACCESS_HAS_MIN :: 64
ACCESS_HAS_MAX :: 128
ACCESS_HAS_SCROLL :: 256
ACCESS_HAS_TEXT_SELECTION :: 512
ACCESS_DISABLED :: 1024
ACCESS_MODAL :: 2048
ACCESS_SELECTED_SET :: 4096
ACCESS_SELECTED :: 8192
ACCESS_EXPANDED_SET :: 16384
ACCESS_EXPANDED :: 32768
ACCESS_HAS_POS_IN_SET :: 65536
ACCESS_HAS_SET_SIZE :: 131072
ACCESS_LIVE_POLITE :: 262144
ACCESS_LIVE_ASSERTIVE :: 524288
ACCESS_MIXED :: 1048576

CELL_BOLD :: 1
CELL_ITALIC :: 2
CELL_UNDERLINE :: 4
CELL_STRIKETHROUGH :: 8
CELL_WIDE :: 16
CELL_WAVY :: 32
CELL_DOTTED :: 64

CELL_CURSOR_BLOCK :: 1
CELL_CURSOR_BAR :: 2
CELL_CURSOR_UNDERLINE :: 3

MENU_CUSTOM :: 0
MENU_SEPARATOR :: 1
MENU_CUT :: 2
MENU_COPY :: 3
MENU_PASTE :: 4
MENU_SELECT_ALL :: 5
MENU_LOOK_UP :: 6

MENU_ITEM_ENABLED :: 1
MENU_ITEM_CHECKED :: 2

MENU_ACTION_SET_CLIPBOARD :: 0
MENU_ACTION_PASTE :: 1
MENU_ACTION_LOOK_UP :: 2
MENU_ACTION_SET_CLIPBOARD_SECRET :: 3

PASTE_CONCEALED :: 1
PASTE_TRANSIENT :: 2

AUDIO_PLAY :: 1
AUDIO_STOP :: 2
AUDIO_SET_VOLUME :: 3
AUDIO_PAUSE :: 4
AUDIO_RESUME :: 5
AUDIO_MASTER_VOLUME :: 6
AUDIO_UNLOAD :: 7

FRAGMENT_IMAGE_NONE :: 0
FRAGMENT_IMAGE_ATLAS :: 1
FRAGMENT_IMAGE_TEXTURE :: 2

MOUSE_PRIMARY :: 0
MOUSE_SECONDARY :: 1
MOUSE_MIDDLE :: 2
MOUSE_OTHER :: 3

BUTTONS_SECONDARY :: 1
BUTTONS_MIDDLE :: 2
BUTTONS_OTHER :: 4

APPEARANCE_UNKNOWN :: 0
APPEARANCE_LIGHT :: 1
APPEARANCE_DARK :: 2

MOTION_UNKNOWN :: 0
MOTION_FULL :: 1
MOTION_REDUCED :: 2

ASSISTIVE_UNKNOWN :: 0
ASSISTIVE_NONE :: 1
ASSISTIVE_LISTENING :: 2

AUDIO_DEVICE_CLOSED :: 0
AUDIO_DEVICE_OPENING :: 1
AUDIO_DEVICE_OPEN :: 2
AUDIO_DEVICE_FAILED :: 3

OP_LIFT :: 0
OP_DARKEN :: 1
OP_RAISE :: 2
OP_ALPHA :: 3
OP_MIX :: 4
OP_READABLE :: 5

OWED_TRANSITION :: 1
OWED_CYCLE :: 2
OWED_DEPART :: 4
OWED_REQUESTED :: 8
OWED_AUTOSCROLL :: 16
OWED_SCROLL :: 32

FRAME_CAUSE_POINTER_MOVE :: 1
FRAME_CAUSE_POINTER_LEAVE :: 2
FRAME_CAUSE_BUTTON :: 4
FRAME_CAUSE_WHEEL :: 8
FRAME_CAUSE_KEY :: 16
FRAME_CAUSE_MODIFIERS :: 32
FRAME_CAUSE_TEXT :: 64
FRAME_CAUSE_PREEDIT :: 128
FRAME_CAUSE_ACCESS :: 256
FRAME_CAUSE_FILE_DRAG :: 512
FRAME_CAUSE_FILES :: 1024
FRAME_CAUSE_FIRST :: 2048
FRAME_CAUSE_WAKE :: 4096
FRAME_CAUSE_HOST :: 8192
FRAME_CAUSE_RESIZE :: 16384
FRAME_CAUSE_SCALE :: 32768
FRAME_CAUSE_FOCUS :: 65536
FRAME_CAUSE_OCCLUSION :: 131072
FRAME_CAUSE_APPEARANCE :: 262144
FRAME_CAUSE_CARET :: 524288
FRAME_CAUSE_RETRY :: 1048576
FRAME_CAUSE_OVERDUE :: 2097152
FRAME_CAUSE_DEVICE :: 4194304
FRAME_CAUSE_AFTER_FRAME :: 8388608
FRAME_CAUSE_ELSEWHERE :: 16777216
FRAME_CAUSE_MENU :: 33554432
FRAME_CAUSE_AUDIO :: 67108864
FRAME_CAUSE_SMOKE :: 134217728
FRAME_CAUSE_OWED :: 268435456

PATH_MOVE :: 0
PATH_LINE :: 1
PATH_QUAD :: 2
PATH_CUBIC :: 3
PATH_ARC :: 4
PATH_CLOSE :: 5

FILL_NONZERO :: 0
FILL_EVENODD :: 1

COPY_READY :: 0
COPY_ASKED :: 1
COPY_NOTHING :: 2

FILE_DIALOG_OPEN :: 0
FILE_DIALOG_SAVE :: 1
FILE_DIALOG_FOLDER :: 2

CHROME_NATIVE :: 0
CHROME_CUSTOM :: 1
CHROME_BORDERLESS :: 2

TEXT_AA_AUTO :: 0
TEXT_AA_GRAYSCALE :: 1
TEXT_AA_SUBPIXEL :: 2

DIAG_DEFAULT :: 0
DIAG_ON :: 1
DIAG_OFF :: 2

// -- Callbacks
ViewFn :: #type proc "c" (rawptr, ^Ctx)
EventFn :: #type proc "c" (rawptr, ^Event)
TeardownFn :: #type proc "c" (rawptr)
ExtViewFn :: #type proc "c" (rawptr, ^Ctx)
ExtEventFn :: #type proc "c" (rawptr, ^Event)

// -- Structs
Sizing :: struct {
	tag: u32,
	value: f32,
}

Keyframe :: struct {
	set: u32,
	at: f32,
	width: Sizing,
	height: Sizing,
	bg: u32,
	radius: f32,
	opacity: f32,
}

GradientStop :: struct {
	color: u32,
	at: f32,
}

Gradient :: struct {
	kind: u32,
	angle: f32,
	at_x: f32,
	at_y: f32,
	stops: [^]GradientStop,
	stops_len: uint,
}

Enter :: struct {
	set: u32,
	dx: f32,
	dy: f32,
	width: Sizing,
	height: Sizing,
	bg: u32,
	radius: f32,
	opacity: f32,
}

Spec :: struct {
	width: Sizing,
	height: Sizing,
	min_w: f32,
	max_w: f32,
	min_h: f32,
	max_h: f32,
	dir: u32,
	pad_l: f32,
	pad_r: f32,
	pad_t: f32,
	pad_b: f32,
	gap: f32,
	main_align: u32,
	cross_align: u32,
	bg: u32,
	border_color: u32,
	border_w: f32,
	radius: f32,
	overflow: u32,
	float_mode: u32,
	float_anchor_x: u32,
	float_anchor_y: u32,
	float_self_x: u32,
	float_self_y: u32,
	float_dx: f32,
	float_dy: f32,
	float_fit: u32,
	hoverable: u32,
	window_role: u32,
	transition_ms: f32,
	easing: u32,
	slide: u32,
	hover_bg: u32,
	pressed_bg: u32,
	hover_group: string,
	per_corner: u32,
	radius_tl: f32,
	radius_tr: f32,
	radius_br: f32,
	radius_bl: f32,
	repeat: u32,
	delay_ms: f32,
	keyframes: [^]Keyframe,
	keyframes_len: uint,
	enter: Enter,
	click_sound: u64,
	hover_sound: u64,
	on_layout: ^Value,
	role: u32,
	label: string,
	checked: u32,
	value_set: u32,
	value_now: f32,
	value_min: f32,
	value_max: f32,
	caret: u32,
	selection_anchor: u32,
	focusable: u32,
	disabled: u32,
	focus_bg: u32,
	tooltip: string,
	modal: ^Value,
	on_context_menu: ^Value,
	cursor: u32,
	selected: u32,
	expanded: u32,
	opacity_set: u32,
	opacity: f32,
	shadow_color: u32,
	shadow_blur: f32,
	shadow_x: f32,
	shadow_y: f32,
	shadow_spread: f32,
	wrap_children: u32,
	cross_gap: f32,
	initial_focus: u32,
	exit: Enter,
	live: u32,
	key_up: u32,
	value_text: string,
	description: string,
	animate: u32,
	accent: u32,
	selectable: u32,
	on_force_click: ^Value,
	focus_region: u32,
	scrollbar: u32,
	scrollbar_width: f32,
	scrollbar_color: u32,
	scrollbar_active_color: u32,
	anchor: u32,
	on_scroll: ^Value,
	on_drop: ^Value,
	drop_bg: u32,
	float_clip: u32,
	aspect_ratio: f32,
	mixed: u32,
	value_step: f32,
	on_change: ^Value,
	pixel_snap: u32,
	keep_focus: u32,
	on_focus: ^Value,
	rules: u32,
	rule_w: f32,
	on_button: ^Value,
	buttons: u32,
	overscroll: u32,
	scroll_axes: u32,
	modifier_keys: u32,
	min_w_size: Sizing,
	max_w_size: Sizing,
	min_h_size: Sizing,
	max_h_size: Sizing,
	bounce: f32,
	gradient: ^Gradient,
	scroll_mods: u32,
}

Announcement :: struct {
	text: string,
	live: u32,
}

AccessNode :: struct {
	key: u64,
	parent: u64,
	origin: u32,
	role: u32,
	flags: u32,
	actions: u32,
	name: string,
	description: string,
	value: string,
	x: f32,
	y: f32,
	w: f32,
	h: f32,
	caret: u32,
	selection_start: u32,
	selection_end: u32,
	value_now: f32,
	value_min: f32,
	value_max: f32,
	scroll_x: f32,
	scroll_y: f32,
	scroll_max_x: f32,
	scroll_max_y: f32,
	anchor_run: u64,
	anchor_char: u32,
	focus_run: u64,
	focus_char: u32,
	run_count: u32,
	pos_in_set: u32,
	set_size: u32,
	orientation: u32,
}

AccessRun :: struct {
	key: u64,
	line: u32,
	start: u32,
	end: u32,
	text: string,
	x: f32,
	y: f32,
	w: f32,
	h: f32,
	char_count: u32,
	char_lengths: [^]u8,
	char_positions: [^]f32,
	char_widths: [^]f32,
	word_start_count: u32,
	word_starts: [^]u8,
	rtl: u32,
}

TextMetrics :: struct {
	size: u32,
	width: f32,
	height: f32,
	lines: u32,
}

Cell :: struct {
	ch: u32,
	fg: u32,
	bg: u32,
	flags: u32,
	ul: u32,
}

MenuItem :: struct {
	label: string,
	role: u32,
	enabled: u32,
	id: ^Value,
	accel: string,
	checked: u32,
}

Menu :: struct {
	label: string,
	items: [^]MenuItem,
	count: uint,
	enabled: u32,
}

MenuAction :: struct {
	size: u32,
	kind: u32,
	text: string,
	html: string,
	x: f32,
	y: f32,
}

TextHit :: struct {
	size: u32,
	line: u32,
	byte: u64,
}

CaretRect :: struct {
	size: u32,
	x: f32,
	y: f32,
	w: f32,
	h: f32,
}

ScrollGeometry :: struct {
	size: u32,
	x: f32,
	y: f32,
	w: f32,
	h: f32,
	content_w: f32,
	content_h: f32,
	offset_x: f32,
	offset_y: f32,
	max_offset_x: f32,
	max_offset_y: f32,
}

Warning :: struct {
	code: string,
	key: u64,
	message: string,
}

Play :: struct {
	volume: f32,
	looped: u32,
	fade_in_ms: f32,
}

Audio :: struct {
	src: u64,
	volume: f32,
	looped: u32,
	paused: u32,
	finish: u32,
}

AudioCommand :: struct {
	kind: u32,
	playback: u64,
	sound: u64,
	volume: f32,
	ms: f32,
	looped: u32,
}

TextStyle :: struct {
	size: f32,
	line_height: f32,
	color: u32,
	family: u32,
	font: u64,
	wrap: u32,
	max_lines: u32,
	ellipsis: u32,
	features: string,
	decoration: u32,
	underline_color: u32,
	underline_style: u32,
}

Span :: struct {
	text: string,
	color: u32,
	flags: u32,
	bg: u32,
	underline_color: u32,
	underline_style: u32,
	bg_radius: f32,
}

WindowConfig :: struct {
	kind: u32,
	width: f32,
	height: f32,
	activates: u32,
	anchor_x: f32,
	anchor_y: f32,
	anchor_w: f32,
	anchor_h: f32,
}

WindowCommand :: struct {
	size: u32,
	kind: u32,
	window: u32,
	origin: u16,
	config: WindowConfig,
	width: f32,
	height: f32,
	owner: u32,
}

Event :: struct {
	size: u32,
	origin: u16,
	key: u64,
	payload: ^Value,
	window: u32,
	reply_sink: ^ReplySink,
	slot: u64,
}

Quad :: struct {
	x: f32,
	y: f32,
	w: f32,
	h: f32,
	color: [4]f32,
	border_color: [4]f32,
	radius: [4]f32,
	border_w: f32,
	blur: f32,
	kind: u32,
	clip: u32,
	uv: [4]u32,
}

Clip :: struct {
	rect: [4]f32,
	radius: [4]f32,
}

FragmentDraw :: struct {
	fragment: u64,
	params: [16]f32,
	image_source: u32,
	image_texture: u32,
	image_uv: [4]u32,
}

TextureDraw :: struct {
	image: u64,
	rev: u32,
	width: u32,
	height: u32,
	uv: [4]u32,
}

DrawData :: struct {
	size: u32,
	quads: [^]Quad,
	quad_count: uint,
	viewport_w: f32,
	viewport_h: f32,
	scale: f32,
	atlas_pixels: [^]u8,
	atlas_size: u32,
	atlas_dirty: bool,
	atlas_epoch: u64,
	fragments: [^]FragmentDraw,
	fragment_count: uint,
	time: f32,
	clips: [^]Clip,
	clip_count: uint,
	textures: [^]TextureDraw,
	texture_count: uint,
}

Theme :: struct {
	size: u32,
	appearance: u32,
	disabled_opacity: f32,
	bg: u32,
	surface: u32,
	raised: u32,
	sunken: u32,
	border: u32,
	border_strong: u32,
	fg: u32,
	muted: u32,
	faint: u32,
	accent: u32,
	accent_hover: u32,
	accent_pressed: u32,
	on_accent: u32,
	accent_soft: u32,
	selection: u32,
	focus_ring: u32,
	hover: u32,
	pressed: u32,
	success: u32,
	warning: u32,
	danger: u32,
	scrollbar: u32,
	scrollbar_active: u32,
}

Metrics :: struct {
	size: u32,
	control_text: f32,
	chrome_text: f32,
	hint_text: f32,
	radius: f32,
	radius_inner: f32,
	control_pad_x: f32,
	control_pad_y: f32,
	field_pad_x: f32,
	field_pad_y: f32,
	hint_pad_x: f32,
	hint_pad_y: f32,
	menu_pad_x: f32,
	menu_pad_y: f32,
	menu_width: f32,
	menu_bar_h: f32,
	titlebar_h: f32,
}

ColorToken :: struct {
	name: string,
	light: u32,
	dark: u32,
}

LengthToken :: struct {
	name: string,
	value: f32,
}

ColorOp :: struct {
	op: u8,
	t: f32,
	other: string,
}

DerivedToken :: struct {
	name: string,
	from: string,
	ops: [^]ColorOp,
	op_count: uint,
}

LayoutRect :: struct {
	size: u32,
	x: f32,
	y: f32,
	w: f32,
	h: f32,
}

SystemFont :: struct {
	family: string,
	weights: [^]u16,
	weight_count: u32,
	monospaced: u32,
	italic: u32,
}

FileFilter :: struct {
	name: string,
	extensions: [^]string,
	extension_count: uint,
}

FileDialog :: struct {
	mode: u32,
	multiple: u32,
	title: string,
	filters: [^]FileFilter,
	filter_count: uint,
	directory: string,
	file_name: string,
}

RunConfig :: struct {
	width: f32,
	height: f32,
	min_w: f32,
	min_h: f32,
	max_w: f32,
	max_h: f32,
	chrome: u32,
	text_aa: u32,
	diagnostics: u32,
	frame_latency: u32,
}

// -- Functions
@(default_calling_convention = "c", link_prefix = "kui_")
foreign lib {
	abi_version :: proc() -> u32 ---
	size_px :: proc(px: f32) -> Sizing ---
	size_pct :: proc(percent: f32) -> Sizing ---
	size_min :: proc(args: [^]Sizing, n: uint) -> Sizing ---
	size_max :: proc(args: [^]Sizing, n: uint) -> Sizing ---
	size_clamp :: proc(lo: Sizing, target: Sizing, hi: Sizing) -> Sizing ---
	size_parse :: proc(s: string, out: ^Sizing) -> bool ---
	ctx_new :: proc() -> ^Ctx ---
	ctx_free :: proc(ctx: ^Ctx) ---
	input_cursor :: proc(ctx: ^Ctx, x: f32, y: f32) ---
	input_cursor_left :: proc(ctx: ^Ctx) ---
	input_mouse :: proc(ctx: ^Ctx, down: bool, clicks: u32) ---
	input_mouse_button :: proc(ctx: ^Ctx, down: bool, button: u32, clicks: u32) ---
	input_scroll :: proc(ctx: ^Ctx, dx: f32, dy: f32) ---
	input_scroll_gesture :: proc(ctx: ^Ctx, dx: f32, dy: f32, begins: bool) ---
	input_text :: proc(ctx: ^Ctx, text: string) ---
	input_commit :: proc(ctx: ^Ctx, text: string) ---
	input_paste :: proc(ctx: ^Ctx, text: string, marks: u32) ---
	input_preedit :: proc(ctx: ^Ctx, text: string, cursor_start: u32, cursor_end: u32) ---
	input_key :: proc(ctx: ^Ctx, key: u32, mods: u32) ---
	input_key_down :: proc(ctx: ^Ctx, code: string, physical: string, kmods: u32, text: string, repeat: bool) ---
	input_key_up :: proc(ctx: ^Ctx, code: string, physical: string, kmods: u32) ---
	input_drag_files :: proc(ctx: ^Ctx, paths: [^]string, count: uint, x: f32, y: f32) ---
	input_drop_files :: proc(ctx: ^Ctx, paths: [^]string, count: uint, x: f32, y: f32) ---
	input_drag_cancel :: proc(ctx: ^Ctx) ---
	input_open :: proc(ctx: ^Ctx, paths: [^]string, count: uint) ---
	input_press :: proc(ctx: ^Ctx, code: string, physical: string, kmods: u32, text: string, repeat: bool) ---
	input_release :: proc(ctx: ^Ctx, code: string, physical: string, kmods: u32) ---
	release_held_keys :: proc(ctx: ^Ctx) ---
	input_modifiers :: proc(ctx: ^Ctx, mods: u32) ---
	poll_event :: proc(ctx: ^Ctx, out: ^Event) -> bool ---
	env_set :: proc(ctx: ^Ctx, refresh_hz: f32, focused: bool) ---
	env_set_system :: proc(ctx: ^Ctx, appearance: u32, accent: u32, motion: u32, locale: string) ---
	env_set_assistive :: proc(ctx: ^Ctx, assistive: u32) ---
	env_set_audio :: proc(ctx: ^Ctx, device: u32, live: u32) ---
	theme :: proc(ctx: ^Ctx, out: ^Theme) -> bool ---
	theme_set_accent :: proc(ctx: ^Ctx, accent: u32) ---
	theme_set :: proc(ctx: ^Ctx, theme: ^Theme) ---
	metrics :: proc(ctx: ^Ctx, out: ^Metrics) -> bool ---
	metrics_set :: proc(ctx: ^Ctx, metrics: ^Metrics) ---
	tokens_set :: proc(ctx: ^Ctx, colors: [^]ColorToken, color_count: uint, lengths: [^]LengthToken, length_count: uint) ---
	token_color :: proc(ctx: ^Ctx, name: string, out: ^u32) -> bool ---
	token_length :: proc(ctx: ^Ctx, name: string, out: ^f32) -> bool ---
	tokens_derive :: proc(ctx: ^Ctx, derived: [^]DerivedToken, count: uint) -> bool ---
	set_time :: proc(ctx: ^Ctx, now_secs: f64) ---
	animating :: proc(ctx: ^Ctx) -> bool ---
	owed :: proc(ctx: ^Ctx) -> u32 ---
	set_frame_trace :: proc(ctx: ^Ctx, on: bool) ---
	frame_cause :: proc(ctx: ^Ctx) -> u32 ---
	note_frame_cause :: proc(ctx: ^Ctx, cause: u32) ---
	frame_unchanged :: proc(ctx: ^Ctx) -> i32 ---
	set_subpixel_text :: proc(ctx: ^Ctx, on: bool) ---
	set_text_cache_budget :: proc(ctx: [^]Ctx, bytes: uint) ---
	text_cache_bytes :: proc(ctx: ^Ctx) -> uint ---
	env_set_window :: proc(ctx: ^Ctx, window: u32, custom_chrome: bool, maximized: bool, fullscreen: bool, controls_w: f32, controls_h: f32) ---
	take_window_command :: proc(ctx: ^Ctx, out: ^WindowCommand) -> bool ---
	window_declare :: proc(ctx: ^Ctx, name: string, cfg: ^WindowConfig) ---
	set_window_size :: proc(ctx: ^Ctx, window: u32, w: f32, h: f32) ---
	focus_window :: proc(ctx: ^Ctx, window: u32) ---
	window_dismissed :: proc(ctx: ^Ctx, id: u32, reason: u32) ---
	ctx_window :: proc(ctx: ^Ctx) -> u32 ---
	ctx_window_name :: proc(ctx: ^Ctx, out: ^string) -> bool ---
	window_closed :: proc(ctx: ^Ctx, id: u32) ---
	cursor_shape :: proc(ctx: ^Ctx) -> u32 ---
	window_title :: proc(ctx: ^Ctx, title: string) ---
	window_title_get :: proc(ctx: ^Ctx, out: ^string) -> bool ---
	set_always_on_top :: proc(ctx: ^Ctx, on_top: bool) ---
	always_on_top_get :: proc(ctx: ^Ctx) -> bool ---
	env_set_always_on_top :: proc(ctx: ^Ctx, always_on_top: bool) ---
	set_secure_input :: proc(ctx: ^Ctx, on: bool) ---
	secure_input_get :: proc(ctx: ^Ctx) -> bool ---
	set_option_as_alt :: proc(ctx: ^Ctx, option_as_alt: u32) ---
	option_as_alt_get :: proc(ctx: ^Ctx) -> u32 ---
	set_ime_off :: proc(ctx: ^Ctx, off: bool) ---
	ime_off_get :: proc(ctx: ^Ctx) -> bool ---
	spec_float_preset :: proc(spec: ^Spec, name: string) -> bool ---
	frame_begin :: proc(ctx: ^Ctx, w: f32, h: f32, scale: f32) ---
	root :: proc(ctx: ^Ctx, spec: ^Spec) ---
	open :: proc(ctx: ^Ctx, spec: ^Spec, on_click: ^Value) -> u64 ---
	open_keyed :: proc(ctx: ^Ctx, label: string, spec: ^Spec, on_click: ^Value) -> u64 ---
	open_indexed :: proc(ctx: ^Ctx, index: u64, spec: ^Spec, on_click: ^Value) -> u64 ---
	row_count :: proc(ctx: ^Ctx, rows: u64) ---
	slot :: proc(ctx: ^Ctx, name: string, params: ^Value) -> bool ---
	ctx_add_extension :: proc(ctx: ^Ctx, namespace_: string, path: string) -> bool ---
	ctx_extension_error :: proc(ctx: ^Ctx, out: ^string) -> bool ---
	ctx_extension_count :: proc(ctx: ^Ctx) -> u32 ---
	ctx_extension_namespace :: proc(ctx: ^Ctx, origin: u16, out: ^string) -> bool ---
	open_draggable :: proc(ctx: ^Ctx, label: string, spec: ^Spec, on_click: ^Value, on_drag: ^Value) -> u64 ---
	open_with :: proc(ctx: ^Ctx, label: string, spec: ^Spec, on_click: ^Value, on_drag: ^Value, on_key: ^Value, on_hover: ^Value) -> u64 ---
	set_key_focus :: proc(ctx: ^Ctx, key: u64) ---
	focus :: proc(ctx: ^Ctx, key: u64) ---
	key_of :: proc(ctx: ^Ctx, label: string) -> u64 ---
	focus_next :: proc(ctx: ^Ctx, forward: bool) ---
	focused :: proc(ctx: ^Ctx) -> u64 ---
	focus_visible :: proc(ctx: ^Ctx) -> bool ---
	caret_visible :: proc(ctx: ^Ctx) -> bool ---
	set_caret_visible :: proc(ctx: ^Ctx, visible: bool) ---
	has_caret :: proc(ctx: ^Ctx) -> bool ---
	caret_stamp :: proc(ctx: ^Ctx) -> u64 ---
	focus_region :: proc(ctx: ^Ctx, key: u64) ---
	region :: proc(ctx: ^Ctx) -> u64 ---
	reveal :: proc(ctx: ^Ctx, key: u64) ---
	set_scroll :: proc(ctx: ^Ctx, key: u64, x: f32, y: f32) ---
	shift_scroll :: proc(ctx: ^Ctx, key: u64, drawn: f32, target: f32) ---
	scroll_offset :: proc(ctx: ^Ctx, key: u64, x: ^f32, y: ^f32) ---
	layout_of :: proc(ctx: ^Ctx, key: u64, out: ^LayoutRect) -> bool ---
	scroll_geometry :: proc(ctx: ^Ctx, key: u64, out: ^ScrollGeometry) -> bool ---
	font_add :: proc(ctx: ^Ctx, data: [^]u8, len: uint) -> u64 ---
	font_add_system :: proc(ctx: ^Ctx, name: string) -> u64 ---
	font_families :: proc(ctx: ^Ctx, out: [^]string, cap: uint) -> uint ---
	system_fonts :: proc(ctx: ^Ctx, out: [^]SystemFont, cap: uint) -> uint ---
	font_load_file :: proc(ctx: ^Ctx, path: string) -> u64 ---
	font_load_dir :: proc(ctx: ^Ctx, dir: string) -> uint ---
	font_reload_system :: proc(ctx: ^Ctx) -> uint ---
	font_set_fallback :: proc(ctx: ^Ctx, ids: [^]u64, len: uint) ---
	font_remove :: proc(ctx: ^Ctx, id: u64) ---
	image_add :: proc(ctx: ^Ctx, w: u32, h: u32, rgba: [^]u8) -> u64 ---
	image_remove :: proc(ctx: ^Ctx, id: u64) ---
	image_update :: proc(ctx: ^Ctx, id: u64, w: u32, h: u32, rgba: [^]u8) ---
	image_pixels :: proc(ctx: ^Ctx, id: u64, w: ^u32, h: ^u32, rgba: ^[^]u8) -> bool ---
	fragment_add :: proc(ctx: ^Ctx, wgsl: string) -> u64 ---
	fragment_remove :: proc(ctx: ^Ctx, id: u64) ---
	fragment_source :: proc(ctx: ^Ctx, id: u64, out: ^string) -> bool ---
	sound_add :: proc(ctx: ^Ctx, data: [^]u8, len: uint) -> u64 ---
	sound_remove :: proc(ctx: ^Ctx, id: u64) ---
	play :: proc(ctx: ^Ctx, sound: u64, opts: ^Play, tag: ^Value) -> u64 ---
	stop :: proc(ctx: ^Ctx, playback: u64, fade_ms: f32) ---
	set_volume :: proc(ctx: ^Ctx, playback: u64, volume: f32, tween_ms: f32) ---
	pause :: proc(ctx: ^Ctx, playback: u64, fade_ms: f32) ---
	resume :: proc(ctx: ^Ctx, playback: u64, fade_ms: f32) ---
	set_master_volume :: proc(ctx: ^Ctx, volume: f32, tween_ms: f32) ---
	audio :: proc(ctx: ^Ctx, label: string, spec: ^Audio, tag: ^Value) -> u64 ---
	take_audio_commands :: proc(ctx: ^Ctx, out: [^]AudioCommand, cap: uint) -> uint ---
	audio_ended :: proc(ctx: ^Ctx, playback: u64) ---
	audio_truncated :: proc(ctx: ^Ctx, playback: u64, at: f64) ---
	audio_refused :: proc(ctx: ^Ctx, playback: u64) ---
	image :: proc(ctx: ^Ctx, id: u64, spec: ^Spec) ---
	image_with :: proc(ctx: ^Ctx, id: u64, sampling: u32, fit: u32, spec: ^Spec) ---
	fragment :: proc(ctx: ^Ctx, id: u64, params: [^]f32, count: uint, spec: ^Spec) ---
	fragment_open :: proc(ctx: ^Ctx, label: string, id: u64, params: [^]f32, count: uint, spec: ^Spec) ---
	fragment_with :: proc(ctx: ^Ctx, label: string, id: u64, image: u64, params: [^]f32, count: uint, spec: ^Spec) ---
	fragment_open_with :: proc(ctx: ^Ctx, label: string, id: u64, image: u64, params: [^]f32, count: uint, spec: ^Spec) ---
	line :: proc(ctx: ^Ctx, x0: f32, y0: f32, x1: f32, y1: f32, width: f32, color: u32, spec: ^Spec) ---
	polyline :: proc(ctx: ^Ctx, label: string, xy: [^]f32, count: uint, width: f32, color: u32, curve: bool, dash: [^]f32, spec: ^Spec, on_click: ^Value, on_drag: ^Value, on_hover: ^Value) ---
	polygon :: proc(ctx: ^Ctx, label: string, xy: [^]f32, count: uint, spec: ^Spec, on_click: ^Value, on_drag: ^Value, on_hover: ^Value) ---
	path :: proc(ctx: ^Ctx, label: string, ops: [^]f32, count: uint, fill_rule: u32, width: f32, color: u32, rotate: f32, pivot: [^]f32, dash: [^]f32, spec: ^Spec, on_click: ^Value, on_drag: ^Value, on_hover: ^Value) ---
	path_parse :: proc(d: string, out: [^]f32, cap: uint) -> uint ---
	path_d :: proc(ctx: ^Ctx, label: string, d: string, fill_rule: u32, width: f32, color: u32, rotate: f32, pivot: [^]f32, dash: [^]f32, spec: ^Spec, on_click: ^Value, on_drag: ^Value, on_hover: ^Value) ---
	close :: proc(ctx: ^Ctx) ---
	text :: proc(ctx: ^Ctx, text: string, style: ^TextStyle) ---
	rich_text :: proc(ctx: ^Ctx, spans: [^]Span, span_count: uint, base: ^TextStyle) ---
	cells :: proc(ctx: ^Ctx, label: string, rows: u32, cols: u32, cells: [^]Cell, count: uint, style: ^TextStyle, spec: ^Spec, on_click: ^Value, on_drag: ^Value, on_key: ^Value, cursor_row: u32, cursor_col: u32, cursor_shape: u32, cursor_color: u32, origin_line: u64) ---
	child_key :: proc(ctx: ^Ctx, label: string) -> u64 ---
	is_hovered :: proc(ctx: ^Ctx, key: u64) -> bool ---
	is_pressed :: proc(ctx: ^Ctx, key: u64) -> bool ---
	is_drop_target :: proc(ctx: ^Ctx, key: u64) -> bool ---
	drop_target :: proc(ctx: ^Ctx) -> u64 ---
	measure_text :: proc(ctx: ^Ctx, text: string, style: ^TextStyle, max_w: f32, out: ^TextMetrics) -> bool ---
	measure_rich_text :: proc(ctx: ^Ctx, spans: [^]Span, span_count: uint, base: ^TextStyle, max_w: f32, out: ^TextMetrics) -> bool ---
	text_hit :: proc(ctx: ^Ctx, key: u64, x: f32, y: f32, out: ^TextHit) -> bool ---
	open_menu :: proc(ctx: ^Ctx, key: u64, x: f32, y: f32, items: [^]MenuItem, count: uint) -> bool ---
	close_menu :: proc(ctx: ^Ctx) -> bool ---
	menu_bar :: proc(ctx: ^Ctx, menus: [^]Menu, count: uint) -> bool ---
	set_native_menu_bar :: proc(ctx: ^Ctx, on: bool) ---
	menu_bar_menu_count :: proc(ctx: ^Ctx, revision: ^u64) -> uint ---
	menu_bar_menu :: proc(ctx: [^]Ctx, menu: uint, label: ^string, enabled: ^bool) -> uint ---
	menu_bar_item :: proc(ctx: [^]Ctx, menu: uint, item: uint, label: ^string, accel: ^string, role: ^u32, flags: ^u32) -> bool ---
	activate_menu_bar_item :: proc(ctx: [^]Ctx, menu: uint, item: uint) -> bool ---
	selection_text :: proc(ctx: ^Ctx, out: ^string) -> bool ---
	selection_html :: proc(ctx: ^Ctx, out: ^string) -> bool ---
	selection_ends :: proc(ctx: ^Ctx, anchor_index: ^i64, anchor_byte: ^uint, focus_index: ^i64, focus_byte: ^uint) -> bool ---
	cell_selection :: proc(ctx: ^Ctx, node: ^u64, anchor_line: ^u64, anchor_col: ^uint, focus_line: ^u64, focus_col: ^uint, block: ^bool) -> bool ---
	select_all_in :: proc(ctx: ^Ctx, key: u64) -> bool ---
	clear_selection :: proc(ctx: ^Ctx) -> bool ---
	request_copy :: proc(ctx: ^Ctx, out: ^string) -> u32 ---
	answer_selection_range :: proc(ctx: ^Ctx, text: string) -> bool ---
	set_clipboard :: proc(ctx: ^Ctx, text: string, html: string) ---
	set_clipboard_secret :: proc(ctx: ^Ctx, text: string) ---
	request_paste :: proc(ctx: ^Ctx) ---
	awaiting_paste :: proc(ctx: ^Ctx) -> bool ---
	set_native_menus :: proc(ctx: ^Ctx, on: bool) ---
	menu_item_count :: proc(ctx: ^Ctx, target: ^u64, x: ^f32, y: ^f32) -> uint ---
	menu_item :: proc(ctx: [^]Ctx, item: uint, label: ^string, accel: ^string, role: ^u32, flags: ^u32) -> bool ---
	activate_menu_item :: proc(ctx: [^]Ctx, index: uint) -> bool ---
	set_lookup_available :: proc(ctx: ^Ctx, on: bool) ---
	take_menu_action :: proc(ctx: ^Ctx, out: ^MenuAction) -> bool ---
	request_files :: proc(ctx: ^Ctx, dialog: ^FileDialog, tag: ^Value) -> bool ---
	awaiting_files :: proc(ctx: ^Ctx) -> bool ---
	take_file_request :: proc(ctx: ^Ctx, mode: ^u32, multiple: ^bool, title: ^string, directory: ^string, file_name: ^string, filter_count: ^uint) -> bool ---
	file_request_filter :: proc(ctx: [^]Ctx, i: uint, name: ^string, extensions: ^string) -> bool ---
	input_files :: proc(ctx: ^Ctx, paths: [^]string, count: uint) ---
	caret_rect :: proc(ctx: ^Ctx, key: u64, byte: uint, out: ^CaretRect) -> bool ---
	ime_rect :: proc(ctx: ^Ctx, out: ^CaretRect) -> bool ---
	take_warnings :: proc(ctx: ^Ctx, out: [^]Warning, cap: uint) -> uint ---
	set_diagnostics :: proc(ctx: ^Ctx, on: bool) ---
	set_devtools :: proc(ctx: ^Ctx, on: bool) ---
	set_devtools_dock :: proc(ctx: ^Ctx, dock: string) -> bool ---
	devtools :: proc(ctx: ^Ctx) -> bool ---
	devtools_dock :: proc(ctx: ^Ctx, out: ^string) -> bool ---
	host_rect :: proc(ctx: ^Ctx, out: ^LayoutRect) -> bool ---
	set_devtools_theme :: proc(ctx: ^Ctx, base: string, accent: u32) -> bool ---
	set_devtools_key :: proc(ctx: ^Ctx, key: string) -> bool ---
	devtools_key :: proc(ctx: ^Ctx, out: ^string) -> bool ---
	devtools_tab :: proc(ctx: ^Ctx, name: string, label: string, slot: string) -> bool ---
	devtools_tab_open :: proc(ctx: ^Ctx, name: string, label: string) -> bool ---
	devtools_selected :: proc(ctx: ^Ctx) -> u64 ---
	devtools_hovered :: proc(ctx: ^Ctx) -> u64 ---
	devtools_picked :: proc(ctx: ^Ctx) -> u64 ---
	set_devtools_selected :: proc(ctx: ^Ctx, key: u64) ---
	set_devtools_pick :: proc(ctx: ^Ctx, on: bool) ---
	devtools_picking :: proc(ctx: ^Ctx) -> bool ---
	set_devtools_tab :: proc(ctx: ^Ctx, name: string) -> bool ---
	devtools_current_tab :: proc(ctx: ^Ctx, out: ^string) -> bool ---
	set_devtools_legend :: proc(ctx: ^Ctx, keys: [^]string, what: [^]string, count: uint) ---
	set_inspect :: proc(ctx: ^Ctx, on: bool) ---
	nodes :: proc(ctx: ^Ctx) -> ^Value ---
	access_tree :: proc(ctx: ^Ctx, out: [^]AccessNode, cap: uint) -> uint ---
	announce :: proc(ctx: ^Ctx, text: string, live: u32) ---
	take_announcements :: proc(ctx: ^Ctx, out: [^]Announcement, cap: uint) -> uint ---
	input_access :: proc(ctx: ^Ctx, key: u64, action: u32, value: string) ---
	access_runs :: proc(ctx: ^Ctx, key: u64, out: [^]AccessRun, cap: uint) -> uint ---
	input_access_text :: proc(ctx: ^Ctx, key: u64, action: u32, anchor_run: u64, anchor_char: u32, focus_run: u64, focus_char: u32, value: string) ---
	button :: proc(ctx: ^Ctx, label: string, payload: ^Value) ---
	button_with :: proc(ctx: ^Ctx, text: string, spec: ^Spec, payload: ^Value) ---
	titlebar :: proc(ctx: ^Ctx, title: string) ---
	titlebar_with :: proc(ctx: ^Ctx, body: ViewFn, user: rawptr) ---
	window_buttons :: proc(ctx: ^Ctx) ---
	tooltip :: proc(ctx: ^Ctx, text: string) ---
	tooltip_with :: proc(ctx: ^Ctx, body: ViewFn, user: rawptr) ---
	latency_graph :: proc(ctx: ^Ctx) ---
	latency_hud :: proc(ctx: ^Ctx, x: u32, y: u32) ---
	text_input :: proc(ctx: ^Ctx, label: string, initial: string) -> u64 ---
	select :: proc(ctx: ^Ctx, label: string, items: [^]MenuItem, count: uint, current: i64) -> u64 ---
	checkbox :: proc(ctx: ^Ctx, text: string, spec: ^Spec, payload: ^Value) -> u64 ---
	radio :: proc(ctx: ^Ctx, text: string, spec: ^Spec, payload: ^Value) -> u64 ---
	@(link_name = "kui_switch")
	switch_ :: proc(ctx: ^Ctx, text: string, spec: ^Spec, payload: ^Value) -> u64 ---
	radio_group_open :: proc(ctx: ^Ctx, label: string, spec: ^Spec) -> u64 ---
	slider :: proc(ctx: ^Ctx, label: string, spec: ^Spec) -> u64 ---
	text_edit :: proc(ctx: ^Ctx, label: string, initial: string, style: ^TextStyle, flags: u32, spec: ^Spec) -> u64 ---
	edit_text :: proc(ctx: ^Ctx, key: u64, out: ^string) -> bool ---
	edit_set_text :: proc(ctx: ^Ctx, key: u64, text: string) ---
	edit_set_text_label :: proc(ctx: ^Ctx, label: string, text: string) ---
	is_focused :: proc(ctx: ^Ctx, key: u64) -> bool ---
	frame_finish :: proc(ctx: ^Ctx) ---
	draw_data :: proc(ctx: ^Ctx, out: ^DrawData) -> bool ---
	value_null :: proc() -> ^Value ---
	value_bool :: proc(v: bool) -> ^Value ---
	value_int :: proc(v: i64) -> ^Value ---
	value_float :: proc(v: f64) -> ^Value ---
	value_str :: proc(s: string) -> ^Value ---
	value_map :: proc() -> ^Value ---
	value_list :: proc() -> ^Value ---
	value_map_set :: proc(map_: ^Value, key: string, val: ^Value) ---
	value_list_push :: proc(list: ^Value, val: ^Value) ---
	value_get :: proc(v: ^Value, key: string) -> ^Value ---
	value_at :: proc(v: [^]Value, i: uint) -> ^Value ---
	value_entry :: proc(v: [^]Value, i: uint, key: ^string) -> ^Value ---
	value_len :: proc(v: ^Value) -> uint ---
	value_is_null :: proc(v: ^Value) -> bool ---
	value_as_bool :: proc(v: ^Value, out: ^bool) -> bool ---
	value_as_int :: proc(v: ^Value, out: ^i64) -> bool ---
	value_as_float :: proc(v: ^Value, out: ^f64) -> bool ---
	value_as_str :: proc(v: ^Value, out: ^string) -> bool ---
	value_free :: proc(v: ^Value) ---
	run :: proc(title: string, view: ViewFn, on_event: EventFn, user: rawptr) -> bool ---
	on_teardown :: proc(teardown: TeardownFn) ---
	set_icon :: proc(rgba: [^]u8, width: u32, height: u32, resource: u32) -> bool ---
	run_with :: proc(ctx: ^Ctx, title: string, config: ^RunConfig, view: ViewFn, on_event: EventFn, user: rawptr) -> bool ---
	slot_name :: proc(ctx: ^Ctx, out: ^string) -> bool ---
	slot_namespace :: proc(ctx: ^Ctx, out: ^string) -> bool ---
	slot_params :: proc(ctx: ^Ctx) -> ^Value ---
	reply :: proc(ev: ^Event, reply: ^Value) -> bool ---
}
