[package]
name = "kui-core"
version.workspace = true
edition.workspace = true

[dependencies]
slotmap.workspace = true
rustc-hash.workspace = true
cosmic-text.workspace = true
swash.workspace = true

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "frame"
harness = false

[[bench]]
name = "editing"
harness = false

[[bench]]
name = "highlight"
harness = false
