// Regenerates everything derived from the prop schema (`kui_core::schema::PROPS`,
// exported by the addon's protocol()):
//   - jsx-runtime.d.ts   the TS prop types (between the generated markers)
//   - ../../docs/props.md the cross-binding reference (JSX / Lua / C names)
// Run after changing the schema: npm run gen. CI fails on stale output.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const native = createRequire(import.meta.url)('./native.cjs');
const { prop, elements, events, resources } = native.protocol();

const TS_BY_KIND = {
  f32: 'number',
  color: 'ColorProp',
  flag: 'boolean',
  sizing: 'SizingProp',
  msg: 'AppMsg',
  // A tag may be null: the behaviour without a tag on its events.
  tag: 'AppMsg | null',
  str: 'string',
  resource: 'string',
  keyframes: 'KeyframeProp[]',
  enter: 'EnterProp',
};

function field([name, def]) {
  const ts = def.kind === 'enum' ? def.values.map((v) => `'${v}'`).join(' | ') : TS_BY_KIND[def.kind];
  return `  /** ${def.doc} */\n  ${name}?: ${ts};`;
}

const entries = Object.entries(prop).filter(([, d]) => d.kind !== 'custom');
const spec = entries.filter(([, d]) => d.target === 'spec');
const style = entries.filter(([, d]) => d.target === 'style');

// ---------------------------------------------------------------- types --

const block = `// -- generated from the addon's prop schema; edit schema.rs, then \`npm run gen\` --
export interface GeneratedSpecProps {
${spec.map(field).join('\n')}
}

export interface GeneratedStyleProps {
${style.map(field).join('\n')}
}
// -- end generated --`;

const path = new URL('./jsx-runtime.d.ts', import.meta.url);
const src = readFileSync(path, 'utf8');
const re = /\/\/ -- generated from the addon's prop schema[\s\S]*?\/\/ -- end generated --/;
if (!re.test(src)) throw new Error('generated-region markers not found in jsx-runtime.d.ts');
writeFileSync(path, src.replace(re, block));
console.log(`jsx-runtime.d.ts: ${spec.length} spec + ${style.length} style props generated`);

// ----------------------------------------------------------------- docs --
// Every table below comes from the schema crate (`PROPS`, `CUSTOM`,
// `ELEMENTS`, `EVENTS`, `RESOURCES`, `C_FIELDS`) through protocol(); this
// file only lays them out.

const TYPE_DOC = {
  f32: 'number',
  color: 'color (`#hex` or `0xRRGGBBAA`)',
  flag: 'boolean',
  sizing: 'sizing (`number` \\| `"fit"` \\| `"grow"` \\| `"N%"`)',
  msg: 'message (any plain data)',
  tag: 'tag (a message merged into the event under `tag`, or `null` for none)',
  str: 'string',
  resource: 'resource handle',
  keyframes: 'keyframe list (`[{ at?, width?, height?, bg?, radius? }, …]`)',
  enter: 'entrance (`{ dx?, dy?, width?, height?, bg?, radius? }`)',
};

const cell = (s) => String(s).replace(/\|/g, '\\|');
const typeOf = (def) => (def.kind === 'enum' ? def.values.map((v) => `\`${v}\``).join(' \\| ') : TYPE_DOC[def.kind]);
const tableOf = (header, rows) =>
  [`| ${header.join(' | ')} |`, `|${header.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.map(cell).join(' | ')} |`)].join('\n');

const propRow = ([name, def]) => [`\`${name}\``, `\`${def.lua}\``, def.c, typeOf(def), def.doc];
const custom = Object.entries(prop).filter(([, d]) => d.kind === 'custom');

const md = `# kui props, elements and events

*Generated by \`npm run gen\` in \`packages/kui\` from the tables in
\`crates/kui-core/src/schema.rs\` — edit those, not this file.*

One prop schema serves every binding: JSX props are camelCase, Lua keys are
their snake_case, and C uses the \`KuiSpec\` / \`KuiTextStyle\` field named
below. Container props apply to \`<box>\` (and to \`<edit>\` / \`<image>\`
where they make sense); text props apply to \`<text>\` and \`<edit>\`.

## Container props

${tableOf(['JSX', 'Lua', 'C', 'type', 'description'], spec.map(propRow))}

## Text props

${tableOf(['JSX', 'Lua', 'C', 'type', 'description'], style.map(propRow))}

## Composite props (hand-written per binding)

${tableOf(['JSX', 'Lua', 'C', 'description'], custom.map(([, d]) => [d.jsx, d.lua, d.c, d.doc]))}

## Elements

${tableOf(['JSX', 'Lua', 'C', 'notes'], elements.map((e) => [e.jsx, e.lua, e.c, e.doc]))}

## Events

Events are plain data: \`{ origin, key, payload }\` from \`pollEvents()\` in
Node, \`on_event(ev)\` in Lua (payload fields plus \`node_key\`), and
\`kui_poll_event\` in C. The payload shapes:

${tableOf(['kind', 'payload', 'when'], events.map((e) => [e.kind, e.payload, e.doc]))}

## Resources

${tableOf(['what', 'Node', 'Lua', 'C'], resources.map((r) => [r.what, r.node, r.lua, r.c]))}

Handles are slotmap keys with a generation: a removed resource's handle is
rejected (an image draws nothing, a font shapes as sans) rather than
aliasing whatever took its slot.
`;

writeFileSync(new URL('../../docs/props.md', import.meta.url), md);
console.log(
  `docs/props.md: ${spec.length + style.length} schema rows, ${custom.length} composites, ${elements.length} elements, ${events.length} events`,
);
